require_relative '../src/author'
require_relative '../src/book'
require_relative '../src/game'
require_relative '../src/genre'
require_relative '../src/items'
require_relative '../src/label'
require_relative '../src/music_album'
